### ISSUE TITLE
Error install desde el wizzard

### ISSUE THREAD

**Issue by Cu4rach4** [odoo-chile/l10n_cl_account_vat_ledger#2]
Me da el siguiente error:

Intenta instalar el módulo 'l10n_cl_account_vat_ledger' que depende del módulo 'report_aeroo'.
Este último módulo no está disponible en su sistema.

No logro encontrar el modulo report_aeroo, existen otros en odoo, pero el mismo!

**Comment by Danisan** [comment]
Te recomiendo revisar la opción de instalar usando docker, que provee todos los módulos sin necesidad de buscar dependencias, ya que docker satisface todas las dependencias necesarias para todos los componentes.

Instrucciones http://www.odoochile.org/page/instalar-con-docker

También puedes instalar las bibliotecas de aeroo mediante esta linea:
pip install git+https://github.com/aeroo/aeroolib.git@master
Esto es para instalar los módulos de aeroo, desde github directamente.
git clone -b 8.0 https://github.com/aeroo/aeroo_reports.git

Pero además necesitarás algunos componentes más de aeroo. Las instrucciones están aca:

http://www.odoochile.org/page/instalar-con-virtualenv
